Repository Fortify-Labs/Fortify, pull requests merged in 2020-08, with the labels that each got.

#67 Minor fixes to historization service
  devops/kubernetes/main.ts
  scripts/build.sh
  services/historization/package.json
  services/historization/src/index.ts
  services/historization/src/services/leaderboardPersistor.ts
Labels: release

#68 Now writing DC_PULL output to a file and processing it then
  scripts/build.sh
Labels: release

#70 Created backend GraphQL queries for pool viewer
  services/backend/.env.example
  services/backend/.eslintrc.json
  services/backend/.graphqlconfig
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/directives/auth.ts
  services/backend/src/graphql/modules/base.ts
  services/backend/src/graphql/modules/debug.ts
  services/backend/src/graphql/modules/pool.ts
  services/backend/src/inversify.config.ts
  services/backend/tsconfig.json
  services/fsm/.eslintrc.json
  services/fsm/package.json
  services/fsm/src/services/stateTransformer.ts
  services/shared/package.json
  services/shared/src/connectors/redis.ts
Labels: enhancement

#73 Background Match History
  devops/kubernetes/main.ts
  services/fsm/.env.example
  services/fsm/package.json
  services/fsm/src/index.ts
  services/fsm/src/inversify.config.ts
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/fsm/src/reducers/public/poolReducer.ts
  services/fsm/src/services/stateTransformer.ts
  services/fsm/tsconfig.json
  services/historization/package.json
  services/historization/src/index.ts
  services/historization/src/inversify.config.ts
  services/historization/src/services/leaderboardPersistor.ts
  services/historization/src/services/matchPersistor.ts
  services/jobs/package.json
  services/jobs/src/inversify.config.ts
  services/jobs/src/scripts/leaderboardImport.ts
  services/shared/.vscode/settings.json
  services/shared/package.json
  services/shared/src/connectors/postgres.ts
  services/shared/src/db/entities/match.ts
  services/shared/src/db/entities/matchPlayer.ts
  services/shared/src/db/entities/matchSlot.ts
  services/shared/src/db/entities/user.ts
  services/shared/src/events/gameEvents.ts
  services/shared/src/services/eventService.ts
  services/shared/src/services/match.ts
  services/shared/src/state.ts
Labels: enhancement

#74 Average mmr calculations refactoring
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/dev.ts
  services/17kmmrbot/src/commands/left.ts
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/inversify.config.ts
  services/17kmmrbot/tsconfig.json
  services/shared/src/definitions/player.ts
  services/shared/src/services/extractor.ts
Labels: rework

#75 Background match history and code refactor
  devops/kubernetes/.env.example
  devops/kubernetes/main.ts
  devops/kubernetes/src/cluster/ingress.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/dev.ts
  services/17kmmrbot/src/commands/left.ts
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/inversify.config.ts
  services/17kmmrbot/tsconfig.json
  services/backend/.env.example
  services/backend/.eslintrc.json
  services/backend/.graphqlconfig
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/directives/auth.ts
  services/backend/src/graphql/modules/base.ts
  services/backend/src/graphql/modules/debug.ts
  services/backend/src/graphql/modules/pool.ts
  services/backend/src/inversify.config.ts
  services/backend/tsconfig.json
  services/fsm/.env.example
  services/fsm/.eslintrc.json
  services/fsm/package.json
  services/fsm/src/index.ts
  services/fsm/src/inversify.config.ts
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/fsm/src/reducers/public/poolReducer.ts
  services/fsm/src/services/stateTransformer.ts
  services/fsm/tsconfig.json
  services/historization/.eslintrc.json
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/index.ts
  services/historization/src/inversify.config.ts
  services/historization/src/services/leaderboardPersistor.ts
  services/historization/src/services/matchPersistor.ts
  services/jobs/package.json
  services/jobs/src/inversify.config.ts
  services/jobs/src/scripts/leaderboardImport.ts
  services/shared/.vscode/settings.json
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/connectors/postgres.ts
  services/shared/src/connectors/redis.ts
  services/shared/src/db/entities/match.ts
  services/shared/src/db/entities/matchPlayer.ts
  services/shared/src/db/entities/matchSlot.ts
  services/shared/src/db/entities/user.ts
  services/shared/src/definitions/player.ts
  services/shared/src/events/gameEvents.ts
  services/shared/src/events/systemEvents.ts
  services/shared/src/services/eventService.ts
  services/shared/src/services/extractor.ts
  services/shared/src/services/match.ts
  services/shared/src/state.ts
Labels: release

#76 Fix event service not awaiting message sending
  devops/kubernetes/src/deployment.ts
  services/17kmmrbot/package.json
  services/backend/package.json
  services/fsm/package.json
  services/historization/package.json
  services/jobs/package.json
  services/shared/package.json
  services/shared/src/services/eventService.ts
Labels: bug, release

#77 Added user id key to game events in FSM
  scripts/build.sh
  services/fsm/package.json
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/shared/package.json
  services/shared/src/connectors/kafka.ts
Labels: release

#78 Fix multiple MatchFinalPlaceEvents sending
  services/fsm/package.json
  services/fsm/src/reducers/public/lobbyReducer.ts
Labels: release

#80 Handler for leaderboard "RequestFailure" in import script
  scripts/vdacdefs2json.py
  services/jobs/package.json
  services/jobs/src/scripts/leaderboardImport.ts
  services/shared/package.json
  services/shared/src/assets/items.json
  units.json
Labels: release

#81 DB cleanup script now only deleting matches from 2 hours ago
  services/jobs/package.json
  services/jobs/src/scripts/dbCleaner.ts
Labels: release

#82 Matches with final places recorded will not be deleted
  services/jobs/package.json
  services/jobs/src/scripts/dbCleaner.ts
Labels: release

#84 Save game mode and average mmr to postgres
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/inversify.config.ts
  services/fsm/.vscode/settings.json
  services/fsm/package.json
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/historization/package.json
  services/historization/src/services/matchPersistor.ts
  services/shared/package.json
  services/shared/src/db/entities/match.ts
  services/shared/src/events/gameEvents.ts
  services/shared/src/services/extractor.ts
  services/shared/src/services/leaderboard.ts
  services/shared/src/services/match.ts
  services/shared/src/state.ts
Labels: enhancement, release

#85 Default value hotfix
  services/fsm/package.json
  services/shared/package.json
  services/shared/src/db/entities/match.ts
Labels: release

#86 Version bump for clean rebuild of services
  services/17kmmrbot/package.json
  services/historization/package.json
Labels: bug, release

#87 Added redis config to backend in k8s
  devops/kubernetes/main.ts
  services/backend/package.json
Labels: bug, release

#88 Bumped jobs package version
  services/jobs/package.json
Labels: bug, release

#90 Setup typeorm migrations in shared library
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/backend/codegen.yml
  services/backend/ormconfig.ts
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/entities/User.ts
  services/fsm/package-lock.json
  services/fsm/package.json
  services/historization/package-lock.json
  services/historization/package.json
  services/jobs/package-lock.json
  services/jobs/package.json
  services/shared/.env.example
  services/shared/ormconfig.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/connectors/postgres.ts
Labels: rework

#92 Add !help command to twitch bot
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/countdown.ts
  services/17kmmrbot/src/commands/help.ts
  services/17kmmrbot/src/commands/left.ts
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/definitions/twitchCommand.ts
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/inversify.config.ts
Labels: enhancement

#93 Help command in bot & migration script execution in shared lib for postgres
  devops/kubernetes/main.ts
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/countdown.ts
  services/17kmmrbot/src/commands/help.ts
  services/17kmmrbot/src/commands/left.ts
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/definitions/twitchCommand.ts
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/inversify.config.ts
  services/backend/codegen.yml
  services/backend/ormconfig.ts
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/entities/User.ts
  services/backend/src/graphql/graphql.ts
  services/fsm/package-lock.json
  services/fsm/package.json
  services/historization/package-lock.json
  services/historization/package.json
  services/jobs/package-lock.json
  services/jobs/package.json
  services/shared/.env.example
  services/shared/ormconfig.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/connectors/postgres.ts
Labels: release

#96 1.0 Backend Implementation
  ToDo.md
  devops/kubernetes/main.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/services/command.ts
  services/backend/.vscode/settings.json
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/graphql.ts
  services/backend/src/graphql/modules/base.ts
  services/backend/src/graphql/modules/debug.ts
  services/backend/src/graphql/modules/gsi.ts
  services/backend/src/graphql/modules/lobby.ts
  services/backend/src/graphql/modules/match.ts
  services/backend/src/graphql/modules/pool.ts
  services/backend/src/graphql/modules/user.ts
  services/backend/src/graphql/pubsub.ts
  services/backend/src/index.ts
  services/backend/src/inversify.config.ts
  services/backend/src/services/steamAuth.ts
  services/fsm/package.json
  services/fsm/src/inversify.config.ts
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/fsm/src/reducers/public/rankTierReducer.ts
  services/fsm/src/services/stateTransformer.ts
  services/gsi-receiver/package-lock.json
  services/gsi-receiver/package.json
  services/historization/package.json
  services/historization/src/services/matchPersistor.ts
  services/jobs/package.json
  services/jobs/src/scripts/dbCleaner.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/auth.ts
  services/shared/src/connectors/influxdb.ts
  services/shared/src/connectors/redis.ts
  services/shared/src/db/entities/match.ts
  services/shared/src/db/entities/matchPlayer.ts
  services/shared/src/db/entities/matchSlot.ts
  services/shared/src/db/entities/user.ts
  services/shared/src/db/migrations/1597095518930-BackendRework.ts
  services/shared/src/events/gameEvents.ts
  services/shared/src/services/extractor.ts
  services/shared/src/services/match.ts
  services/shared/src/state.ts
Labels: enhancement, rework

#98 Added rate limiting to gsi receiver service
  devops/kubernetes/main.ts
  services/gsi-receiver/package-lock.json
  services/gsi-receiver/package.json
  services/gsi-receiver/src/auth.ts
  services/gsi-receiver/src/index.ts
  services/gsi-receiver/src/inversify.config.ts
Labels: enhancement

#107 Season 2 preparation
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/left.ts
  services/fsm/package.json
  services/fsm/src/services/poolCalculator.ts
  services/shared/package.json
  services/shared/src/db/entities/match.ts
  services/shared/src/db/migrations/1597163264058-SeasonField.ts
  services/shared/src/services/match.ts
  services/shared/src/units.ts
Labels: rework

#110 Navbar component
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/debug.ts
  services/frontend/.env.example
  services/frontend/.vscode/settings.json
  services/frontend/components/footer.tsx
  services/frontend/components/navbar.tsx
  services/frontend/css/_appStyles.module.css
  services/frontend/gql/Authenticated.graphql
  services/frontend/lib/with-apollo.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/_app.tsx
  services/frontend/pages/index.tsx
  services/frontend/pages/lobby.tsx
  services/frontend/pages/matches.tsx
  services/frontend/pages/profile/[id].tsx
  services/frontend/public/favicon.ico
  services/frontend/public/images/Fortify_WIP.png
  services/frontend/sass/darkly/_overrides.scss
  services/frontend/sass/darkly/_variables.scss
  services/frontend/sass/darkly/bulmaswatch.scss
  services/frontend/sass/mystyles.scss
  services/frontend/schema.json
  services/frontend/schema.json.d.ts
  services/frontend/utils/cookie.ts
Labels: enhancement

#112 Footer component
  services/frontend/components/footer.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/imprint.tsx
  services/frontend/pages/privacy.tsx
  services/frontend/sass/mystyles.scss
Labels: enhancement

#118 Matches Page
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/match.ts
  services/backend/src/graphql/pubsub.ts
  services/frontend/.vscode/settings.json
  services/frontend/gql/CurrentMatches.graphql
  services/frontend/pages/matches.tsx
  services/frontend/schema.json
  services/fsm/package.json
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/db/entities/matchPlayer.ts
  services/shared/src/db/migrations/1597425777159-MatchPlayerName.ts
  services/shared/src/services/match.ts
Labels: enhancement

#119 Imprint Page
  services/frontend/package.json
  services/frontend/pages/imprint.tsx
Labels: enhancement

#122 Profile Page
  services/backend/package.json
  services/backend/src/graphql/modules/user.ts
  services/backend/src/services/steamAuth.ts
  services/frontend/.vscode/settings.json
  services/frontend/components/hstack.tsx
  services/frontend/components/linechart.tsx
  services/frontend/components/navbar.tsx
  services/frontend/components/profile/mmrHistory.tsx
  services/frontend/components/profile/recentMatches.tsx
  services/frontend/components/vstack.tsx
  services/frontend/gql/Profile.graphql
  services/frontend/gql/ProfileMatch.graphql
  services/frontend/gql/ProfileMmrHistory.graphql
  services/frontend/lib/with-apollo.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/imprint.tsx
  services/frontend/pages/index.tsx
  services/frontend/pages/profile/[id].tsx
  services/historization/package-lock.json
  services/historization/package.json
Labels: enhancement

#123 Add cookie consent box
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/_app.tsx
Labels: enhancement

#132 Create GSI file using HTML5 in browser
  services/backend/package.json
  services/backend/src/inversify.config.ts
  services/frontend/.vscode/settings.json
  services/frontend/components/gsiModal.tsx
  services/frontend/components/lobby/summary.tsx
  services/frontend/gql/GsiToken.graphql
  services/frontend/gql/LobbySubscription.graphql
  services/frontend/lib/gsiFileGenerator.tsx
  services/frontend/package.json
  services/frontend/pages/index.tsx
  services/frontend/pages/lobby/[[...id]].tsx
  services/frontend/schema.json
Labels: enhancement

#134 Add mechanic to ban / suspend a user
  services/backend/package.json
  services/backend/src/services/steamAuth.ts
  services/shared/package.json
  services/shared/src/db/entities/user.ts
  services/shared/src/db/migrations/1597525293511-MatchPlayerRemoval.ts
  services/shared/src/db/migrations/1597616124879-UserSuspension.ts
Labels: enhancement

#135 Disable / enable new account signups
  services/backend/.vscode/settings.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/debug.ts
  services/backend/src/services/steamAuth.ts
Labels: enhancement

#136 User entity ToS accepted property
  services/shared/package.json
  services/shared/src/db/entities/user.ts
  services/shared/src/db/migrations/1597617691496-UserToSAccepted.ts
Labels: enhancement

#137 Add page titles & SEO
  devops/kubernetes/main.ts
  services/frontend/.env.example
  services/frontend/.vscode/settings.json
  services/frontend/components/lobby/pool.tsx
  services/frontend/components/lobby/summary.tsx
  services/frontend/next-seo.config.ts
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/_app.tsx
  services/frontend/pages/about.tsx
  services/frontend/pages/imprint.tsx
  services/frontend/pages/index.tsx
  services/frontend/pages/lobby/[[...id]].tsx
  services/frontend/pages/matches.tsx
  services/frontend/pages/privacy.tsx
  services/frontend/pages/profile/[id].tsx
Labels: enhancement

#139 Public Player Profiles
  services/backend/package.json
  services/backend/src/graphql/modules/user.ts
  services/shared/package.json
  services/shared/src/db/entities/user.ts
  services/shared/src/db/migrations/1597621709001-PublicPlayerProfiles.ts
Labels: enhancement

#143 Public Player Profile UI Switch
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/user.ts
  services/frontend/gql/Profile.graphql
  services/frontend/gql/UpdateProfile.graphql
  services/frontend/package.json
  services/frontend/pages/profile/[id].tsx
  services/frontend/schema.json
Labels: enhancement

#141 Added GSI setup instructions
  services/frontend/components/gsiModal.tsx
Labels: enhancement

#144 More unit aliases
  services/shared/src/assets/unit_mappings.json
Labels: enhancement

#146 Privacy Policy Page
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/user.ts
  services/frontend/components/lobby/pool.tsx
  services/frontend/gql/UpdateProfile.graphql
  services/frontend/pages/imprint.tsx
  services/frontend/pages/index.tsx
  services/frontend/pages/privacy.tsx
  services/frontend/pages/profile/[id].tsx
  services/frontend/schema.json
Labels: enhancement

#148 Fixed backend using wrong env variable
  services/backend/.env.example
  services/backend/package.json
  services/backend/src/services/steamAuth.ts
Labels: release

#149 Frontend Build Envs
  .env.example
  .gitlab-ci.yml
  build.docker-compose.yml
  devops/kubernetes/main.ts
  services/frontend/lib/with-apollo.tsx
  services/frontend/package.json
  services/shared/src/db/migrations/1597095518930-BackendRework.ts
Labels: release

#150 Fix env variables destructuring in frontend
  services/frontend/lib/with-apollo.tsx
  services/frontend/package.json
Labels: release

#151 Removed rate limiting from services
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/services/steamAuth.ts
  services/gsi-receiver/package-lock.json
  services/gsi-receiver/package.json
  services/gsi-receiver/src/index.ts
Labels: release

#152 Dot Env File Included In Frontend Build
  .dockerignore
  .env.example
  .gitlab-ci.yml
  build.docker-compose.yml
  services/frontend/lib/with-apollo.tsx
  services/frontend/package.json
  services/shared/package.json
  services/shared/src/db/migrations/1597712596401-UserDateFields.ts
Labels: release

#153 Destructured env varibales exchanged with full name
  services/frontend/components/navbar.tsx
  services/frontend/next-seo.config.ts
  services/frontend/pages/imprint.tsx
  services/frontend/pages/index.tsx
  services/frontend/pages/lobby/[[...id]].tsx
  services/frontend/pages/matches.tsx
  services/frontend/pages/privacy.tsx
  services/frontend/pages/profile/[id].tsx
Labels: release

#154 Fixes to logout in Frontend
  services/frontend/package.json
  services/frontend/utils/cookie.ts
Labels: release

#155 Bug fixes and minor tweaks
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
  services/frontend/package.json
  services/frontend/pages/profile/[id].tsx
  services/historization/package.json
  services/historization/src/services/leaderboardPersistor.ts
  services/jobs/package.json
  services/jobs/src/scripts/dbCleaner.ts
Labels: enhancement

#156 Backend authentication fixes
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/debug.ts
  services/backend/src/graphql/modules/user.ts
Labels: release

#157 Removed self-made reconnect from bot
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
Labels: release

#158 Added 1 second sleep between sending announcement messages
  services/17kmmrbot/package.json
  services/17kmmrbot/src/services/command.ts
Labels: release

#159 Silence Bot Broadcast Via Env Variable
  devops/kubernetes/main.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/services/command.ts
  services/frontend/components/linechart.tsx
  services/frontend/lib/useWindowSize.ts
  services/frontend/package.json
Labels: bug, release

#160 Fixed bot subscribing to beginning of topic
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
Labels: bug, release

#161 Promo every other hour
  devops/kubernetes/main.ts
Labels: release

#162 Fixed Kafka Consumer Timeout Issues
  devops/kubernetes/main.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/services/command.ts
  services/fsm/package.json
  services/fsm/src/index.ts
  services/historization/package.json
  services/historization/src/index.ts
Labels: bug, release

#163 Removed instant message resolving in FSM and Historization
  services/fsm/package.json
  services/fsm/src/index.ts
  services/historization/package.json
  services/historization/src/index.ts
Labels: bug, release

#164 Lobbies now viewable by everyone
  devops/kubernetes/main.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/match.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/inversify.config.ts
  services/17kmmrbot/src/lib/dateUtils.ts
  services/17kmmrbot/src/services/command.ts
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/lobby.ts
  services/frontend/package.json
  services/frontend/pages/lobby/[[...id]].tsx
Labels: release

#165 Increased bot wait time to two seconds
  devops/kubernetes/main.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/services/command.ts
Labels: bug, release

#166 Fixed bot time display
  devops/kubernetes/main.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/services/command.ts
Labels: bug, release

#169 Added message timestamps and recording mmr for everyone
  services/fsm/package.json
  services/fsm/src/gsiTypes.ts
  services/fsm/src/index.ts
  services/gsi-receiver/package.json
  services/gsi-receiver/src/index.ts
  services/historization/package.json
  services/historization/src/index.ts
  services/historization/src/services/matchPersistor.ts
  services/shared/package.json
  services/shared/src/events/events.ts
  services/shared/src/events/gameEvents.ts
Labels: enhancement, release

#171 Mapped units names to human readable names in pool viewer
  services/frontend/components/lobby/pool.tsx
  services/frontend/package.json
Labels: enhancement, release

#172 Twitch Account Linking Self Service
  devops/kubernetes/main.ts
  services/backend/.vscode/settings.json
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/user.ts
  services/backend/src/index.ts
  services/backend/src/services/twitchAuth.ts
  services/frontend/gql/UpdateProfile.graphql
  services/frontend/package.json
  services/frontend/pages/profile/[[...id]].tsx
  services/frontend/schema.json
  services/shared/package.json
  services/shared/src/db/entities/user.ts
  services/shared/src/db/migrations/1597939719749-RawTwitchResponseField.ts
Labels: enhancement

#173 Twitch Account Linking
  devops/kubernetes/main.ts
  services/backend/.vscode/settings.json
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/user.ts
  services/backend/src/index.ts
  services/backend/src/services/twitchAuth.ts
  services/frontend/components/lobby/pool.tsx
  services/frontend/gql/UpdateProfile.graphql
  services/frontend/package.json
  services/frontend/pages/profile/[[...id]].tsx
  services/frontend/schema.json
  services/shared/package.json
  services/shared/src/db/entities/user.ts
  services/shared/src/db/migrations/1597939719749-RawTwitchResponseField.ts
Labels: release

#174 Fixed profile page reload bug
  services/frontend/components/navbar.tsx
  services/frontend/package.json
  services/frontend/pages/profile/[[...id]].tsx
Labels: bug, release

#178 Fixed user matches not being sorted by update date
  devops/kubernetes/main.ts
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/graphql/modules/user.ts
Labels: bug, release

#180 Prefix name in !mmr to avoid command confusion
  devops/kubernetes/main.ts
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/mmr.ts
Labels: bug, release

#184 MMR graph does not distinguish between Knockout and Standard MMR
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/reducers/public/rankTierReducer.ts
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/services/matchPersistor.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/events/gameEvents.ts
Labels: bug

#185 MMR data points falsely tagged as standard on rank update event handling
  devops/kubernetes/main.ts
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/reducers/public/rankTierReducer.ts
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/services/matchPersistor.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/events/gameEvents.ts
Labels: bug, release

#186 Match Pool Text Gradient
  services/frontend/components/lobby/pool.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
Labels: enhancement

#187 Add hyperlinking from match lobby to fortify profiles
  services/frontend/components/lobby/summary.tsx
  services/frontend/package.json
Labels: enhancement

#188 UI & UX improvements
  .vscode/settings.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
  services/backend/package.json
  services/backend/src/graphql/modules/user.ts
  services/frontend/components/lobby/pool.tsx
  services/frontend/components/lobby/summary.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
Labels: enhancement, release

#189 Added new rotation units.json & icons
  services/17kmmrbot/package.json
  services/frontend/package.json
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_death_prophet_png.png
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_meepo_png.png
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_pangolier_png.png
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_rubick_png.png
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_skeleton_king_png.png
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_spectre_png.png
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_spirit_breaker_png.png
  services/frontend/public/units/panorama/images/heroes/icons/npc_dota_hero_vengefulspirit_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_death_prophet_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_meepo_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_pangolier_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_rubick_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_skeleton_king_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_spectre_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_spirit_breaker_png.png
  services/frontend/public/units/panorama/images/heroes/portraits/npc_dota_hero_vengefulspirit_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_death_prophet_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_meepo_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_pangolier_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_rubick_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_skeleton_king_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_spectre_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_spirit_breaker_png.png
  services/frontend/public/units/panorama/images/heroes/portraits_wide/npc_dota_hero_vengefulspirit_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/beastmaster_wild_alliance_bonus_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/death_prophet_exorcism_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/enchantress_wild_alliance_bonus_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/lich_frost_shield_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/lone_druid_wild_alliance_bonus_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/magnus_wild_alliance_bonus_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/meepo_divided_we_stand_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/meepo_poof_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/natures_prophet_wild_alliance_bonus_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/pangolier_shield_crash_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/rubick_fade_bolt_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/rubick_spell_steal_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/spectre_spectral_dagger_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/spirit_breaker_charge_of_darkness_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/treant_protector_wild_alliance_bonus_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/vengefulspirit_wave_of_terror_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/wild_alliance_crit_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/wild_alliance_evasion_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/wild_alliance_splash_attack_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/wild_alliance_wrath_of_nature_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/wraith_king_raise_dead_png.png
  services/frontend/public/units/panorama/images/heroes/spellicons/wraith_king_wraithfire_blast_png.png
  services/fsm/package.json
  services/shared/package.json
  services/shared/src/assets/s1_5_units.json
  services/shared/src/units.ts
Labels: release

#190 Historization service more fault tolerant
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#191 Fixed random slot number out of integer range
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#192 Added Math floor to avoid floating point numbers in place fo integers
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#193 In depth error tracking and omitting events with empty matchID
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#194 Saving match before rest to avoid non-existing id references
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#196 Handle duplicate match started events in match service
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#197 Gracefully delete old match slots on multiple match start events
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#199 Skip repetitive match started events
  services/historization/package.json
  services/shared/package.json
  services/shared/src/services/match.ts
Labels: bug, hotfix, release

#201 Updated aliases for new rotation
  devops/kubernetes/src/charts/clusterClean.ts
  devops/kubernetes/src/cluster/ingressTraefik.ts
  services/17kmmrbot/package.json
  services/frontend/package.json
  services/shared/src/assets/unit_mappings.json
Labels: release

#202 Version bumps
  services/17kmmrbot/package.json
  services/frontend/package.json
  services/shared/package.json
Labels: dependencies
