Repository Fortify-Labs/Fortify, pull requests merged in 2020-10, with the labels that each got.

#222 Rework build.sh into github action build job
  .github/workflows/cicd.yml
  .vscode/settings.json
  CLA.md
Labels: infrastructure, rework

#223 Integrate Sentry Into Frontend
  services/frontend/.env.example
  services/frontend/components/linechart.tsx
  services/frontend/next.config.js
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/404.tsx
  services/frontend/pages/_app.tsx
  services/frontend/pages/_error.tsx
Labels: enhancement

#224 Sentry.io integrated into Frontend and CI reworks
  .github/workflows/cicd.yml
  .vscode/settings.json
  CLA.md
  services/frontend/.env.example
  services/frontend/components/linechart.tsx
  services/frontend/next.config.js
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/404.tsx
  services/frontend/pages/_app.tsx
  services/frontend/pages/_error.tsx
Labels: enhancement, infrastructure, rework

#225 CI/CD fix
  .github/workflows/cicd.yml
Labels: infrastructure, rework

#236 Rework user information in gsi topic
  .github/workflows/cicd.yml
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/gsiTypes.ts
  services/fsm/src/index.ts
  services/gsi-receiver/package-lock.json
  services/gsi-receiver/package.json
  services/gsi-receiver/src/index.ts
  services/gsi-receiver/src/inversify.config.ts
Labels: rework

#237 Rework user information in gsi topic
  .github/workflows/cicd.yml
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/gsiTypes.ts
  services/fsm/src/index.ts
  services/gsi-receiver/package-lock.json
  services/gsi-receiver/package.json
  services/gsi-receiver/src/index.ts
  services/gsi-receiver/src/inversify.config.ts
Labels: rework

#238 Fix not storing a rank point for non-lord players
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/services/matchPersistor.ts
Labels: hotfix, release

#243 Influxdb 2 rc switch and left command tier display
  .vscode/settings.json
  devops/kubernetes/.vscode/settings.json
  devops/kubernetes/imports/networking.istio.io/envoyfilter.ts
  devops/kubernetes/imports/networking.istio.io/virtualservice.ts
  devops/kubernetes/imports/security.istio.io/authorizationpolicy.ts
  devops/kubernetes/main.ts
  devops/kubernetes/package-lock.json
  devops/kubernetes/package.json
  devops/kubernetes/setup/setup.sh
  devops/kubernetes/setup/traefik.yaml
  devops/kubernetes/src/charts/clusterClean.ts
  services/17kmmrbot/.eslintrc.json
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/credits.ts
  services/17kmmrbot/src/commands/left.ts
Labels: enhancement, release, rework

#246 Added Pod Disruption Budgets
  devops/kubernetes/.vscode/settings.json
  devops/kubernetes/main.ts
  devops/kubernetes/src/deployment.ts
Labels: infrastructure

#248 Error on update profile checkbox
  services/frontend/components/profile/recentMatches.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/profile/[[...id]].tsx
Labels: bug, rework

#249 Hotfix: Fixed left command
  devops/kubernetes/.vscode/settings.json
  devops/kubernetes/main.ts
  devops/kubernetes/src/deployment.ts
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/left.ts
  services/frontend/components/profile/recentMatches.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/profile/[[...id]].tsx
Labels: bug, hotfix, release

#250 Add own leaderboard
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/leaderboard.ts
  services/backend/src/inversify.config.ts
  services/frontend/components/linechart.tsx
  services/frontend/components/navbar.tsx
  services/frontend/gql/Leaderboard.graphql
  services/frontend/package.json
  services/frontend/pages/leaderboard/[[...leaderboard]].tsx
  services/frontend/schema.json
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/services/leaderboardPersistor.ts
  services/jobs/package-lock.json
  services/jobs/package.json
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/definitions/leaderboard.ts
Labels: enhancement

#251 Added own leaderboard
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/leaderboard.ts
  services/backend/src/inversify.config.ts
  services/frontend/components/linechart.tsx
  services/frontend/components/navbar.tsx
  services/frontend/gql/Leaderboard.graphql
  services/frontend/package.json
  services/frontend/pages/leaderboard/[[...leaderboard]].tsx
  services/frontend/schema.json
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/services/leaderboardPersistor.ts
  services/jobs/package-lock.json
  services/jobs/package.json
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/definitions/leaderboard.ts
Labels: enhancement, release

#253 Hide twitch unlink button from non-authorized users
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/profile/[[...id]].tsx
Labels: release, rework

#254 Refactored mmr tracking and display in frontend
  services/backend/package-lock.json
  services/backend/package.json
  services/backend/src/definitions/graphql/types.ts
  services/backend/src/graphql/modules/leaderboard.ts
  services/backend/src/graphql/modules/match.ts
  services/backend/src/graphql/modules/user.ts
  services/frontend/components/linechart.tsx
  services/frontend/components/lobby/summary.tsx
  services/frontend/components/profile/mmrHistory.tsx
  services/frontend/gql/Leaderboard.graphql
  services/frontend/gql/Lobby.graphql
  services/frontend/gql/LobbySubscription.graphql
  services/frontend/gql/Profile.graphql
  services/frontend/gql/ProfileMmrHistory.graphql
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/leaderboard/[[...leaderboard]].tsx
  services/frontend/pages/profile/[[...id]].tsx
  services/frontend/schema.json
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/services/leaderboardPersistor.ts
  services/historization/src/services/matchPersistor.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/connectors/postgres.ts
  services/shared/src/db/entities/user.ts
  services/shared/src/db/migrations/1603126469995-UserRatings.ts
  services/shared/src/ranks.ts
  services/shared/src/services/match.ts
Labels: release, rework

#255 Hotfix for empty rating object in historization
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/services/matchPersistor.ts
Labels: hotfix, release

#256 Frontend optimizations and added compression
  devops/kubernetes/src/charts/clusterClean.ts
  devops/kubernetes/src/webservice.ts
  services/frontend/components/lobby/pool.tsx
  services/frontend/components/lobby/summary.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
  services/frontend/pages/index.tsx
  services/frontend/pages/leaderboard/[[...leaderboard]].tsx
  services/frontend/public/images/flattened-bg-min.png
Labels: release, rework

#258 Twitch bot version bump
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/match.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
Labels: hotfix

#259 Added Sentry to 17kmmrbot
  devops/kubernetes/main.ts
  services/17kmmrbot/.env.example
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/dev.ts
  services/17kmmrbot/src/commands/match.ts
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/lib/sentryUtils.ts
  services/17kmmrbot/tsconfig.json
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/index.ts
  services/shared/tsconfig.json
Labels: enhancement, release

#260 Added sentry to gsi-receiver
  .github/workflows/cicd.yml
  build.docker-compose.yml
  devops/docker/Base.Dockerfile
  devops/docker/Node.Dockerfile
  devops/docker/NodeExposed.Dockerfile
  devops/kubernetes/.env.example
  devops/kubernetes/main.ts
  devops/kubernetes/src/charts/clusterClean.ts
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
  services/gsi-receiver/.env.example
  services/gsi-receiver/package-lock.json
  services/gsi-receiver/package.json
  services/gsi-receiver/src/index.ts
  services/gsi-receiver/tsconfig.json
Labels: release, rework

#261 Node Docker files match same workdir in final image
  devops/docker/Node.Dockerfile
Labels: release, rework

#262 Added sentry to FSM and made it resistant to kafka crashes
  devops/docker/Node.Dockerfile
  devops/docker/NodeExposed.Dockerfile
  devops/kubernetes/.env.example
  devops/kubernetes/main.ts
  services/fsm/.env.example
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/index.ts
  services/fsm/tsconfig.json
Labels: release, rework

#263 Added sentry to jobs and historization
  devops/kubernetes/.env.example
  devops/kubernetes/main.ts
  devops/kubernetes/src/cronjob.ts
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/index.ts
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/index.ts
  services/jobs/.env.example
  services/jobs/package-lock.json
  services/jobs/package.json
  services/jobs/src/index.ts
  services/jobs/src/scripts/broadcastNotifications.ts
  services/jobs/src/scripts/leaderboardImport.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/db/entities/user.ts
  services/shared/src/services/match.ts
Labels: release, rework

#264 Added missing sentry-cli in dev dependencies
  services/historization/package-lock.json
  services/historization/package.json
  services/jobs/package-lock.json
  services/jobs/package.json
Labels: hotfix, release

#265 Send stringified kafka message to sentry
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/index.ts
  services/historization/package-lock.json
  services/historization/package.json
  services/historization/src/index.ts
Labels: release
