Repository Fortify-Labs/Fortify, pull requests merged in 2020-07, with the labels that each got.

#7 Feature/issue 6
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/services/extractor.ts
Labels: bug, enhancement

#10 Added !np error message when all 8 players aren't in
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/notablePlayers.ts
Labels: bug

#11 Hotfix: Upstart 1 conflict with inactive lord rank resolved
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/notablePlayers.ts
Labels: bug

#12 Hotfix: Fix double print for upstart 1 and inactive lord
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/notablePlayers.ts
Labels: bug

#14 Refactored inidividual command topics to generalized event architecture
  architecture.drawio
  docs/Events.md
  docs/assets/event_driven_architecture.png
  services/17kmmrbot/.vscode/settings.json
  services/17kmmrbot/src/commands/dev.ts
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/services/command.ts
  services/backend/src/graphql/modules/debug.ts
  services/fsm/src/definitions/commandReducer.ts
  services/fsm/src/index.ts
  services/fsm/src/reducers/commands.ts
  services/shared/.vscode/settings.json
  services/shared/src/17kmmrbot.ts
  services/shared/src/events/events.ts
  services/shared/src/events/gameEvents.ts
  services/shared/src/events/genericEvents.ts
  services/shared/src/events/systemEvents.ts
  services/shared/src/index.ts
  services/shared/src/state.ts
Labels: enhancement

#15 Moving from command-centric to generalized event architecture
  architecture.drawio
  docs/Events.md
  docs/assets/event_driven_architecture.png
  services/17kmmrbot/.vscode/settings.json
  services/17kmmrbot/src/commands/dev.ts
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/services/command.ts
  services/backend/src/graphql/modules/debug.ts
  services/fsm/src/definitions/commandReducer.ts
  services/fsm/src/index.ts
  services/fsm/src/reducers/commands.ts
  services/shared/.vscode/settings.json
  services/shared/src/17kmmrbot.ts
  services/shared/src/events/events.ts
  services/shared/src/events/gameEvents.ts
  services/shared/src/events/genericEvents.ts
  services/shared/src/events/systemEvents.ts
  services/shared/src/index.ts
  services/shared/src/state.ts
Labels: enhancement

#26 Create import service typescript project
  services/jobs/.dockerignore
  services/jobs/.env.example
  services/jobs/.eslintignore
  services/jobs/.eslintrc.json
  services/jobs/.prettierrc.js
  services/jobs/.vscode/launch.json
  services/jobs/.vscode/settings.json
  services/jobs/.vscode/tasks.json
  services/jobs/nodemon.json
  services/jobs/package-lock.json
  services/jobs/package.json
  services/jobs/src/index.ts
  services/jobs/src/inversify.config.ts
  services/jobs/src/scripts.d.ts
  services/jobs/src/scripts/dummy.ts
  services/jobs/tsconfig.json
Labels: enhancement

#30 Create a simple import script
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/definitions/leaderboard.ts
  services/17kmmrbot/src/services/extractor.ts
  services/17kmmrbot/src/services/leaderboard.ts
  services/jobs/.env.example
  services/jobs/package-lock.json
  services/jobs/package.json
  services/jobs/src/index.ts
  services/jobs/src/inversify.config.ts
  services/jobs/src/scripts/leaderboardImport.ts
  services/shared/.vscode/settings.json
  services/shared/src/events/systemEvents.ts
Labels: enhancement

#32 Create CronJob constructs in cdk8s
  devops/kubernetes/main.ts
  devops/kubernetes/src/cronjob.ts
  devops/kubernetes/src/deployment.ts
  services/gsi-receiver/.env.example
  services/shared/src/connectors/kafka.ts
Labels: enhancement

#35 Fix missing file in shared library
  devops/docker/Node.Dockerfile
  devops/docker/NodeExposed.Dockerfile
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/mmr.ts
  services/17kmmrbot/src/commands/notablePlayers.ts
  services/17kmmrbot/src/services/extractor.ts
  services/17kmmrbot/src/services/leaderboard.ts
  services/jobs/src/scripts/leaderboardImport.ts
  services/shared/src/definitions/leaderboard.ts
  services/shared/src/events/systemEvents.ts
Labels: release

#36 Scuttle configs and CronJobs for turbo and duos
  devops/docker/Node.Dockerfile
  devops/docker/NodeExposed.Dockerfile
  devops/kubernetes/.vscode/settings.json
  devops/kubernetes/main.ts
  devops/kubernetes/src/cronjob.ts
  devops/kubernetes/src/deployment.ts
  services/17kmmrbot/package.json
  services/backend/package.json
  services/frontend/package.json
  services/fsm/package.json
  services/gsi-receiver/package.json
  services/jobs/package.json
Labels: release

#37 Frontend Apollo v3 migration & cdk8s fixes
  devops/kubernetes/main.ts
  services/frontend/lib/with-apollo.tsx
  services/frontend/package-lock.json
  services/frontend/package.json
Labels: release

#40 Create custom docker base image
  build.docker-compose.yml
  devops/docker/Base.Dockerfile
  devops/docker/Node.Dockerfile
  devops/docker/NodeExposed.Dockerfile
  scripts/build.sh
  services/shared/package.json
Labels: rework

#41 Change 17kmmrbot to fetch leaderboards from redis
  .vscode/settings.json
  devops/kubernetes/main.ts
  services/17kmmrbot/.env.example
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/services/leaderboard.ts
  services/17kmmrbot/tsconfig.json
Labels: rework

#42 17kmmrbot fetching leaderboards from redis
  .vscode/settings.json
  build.docker-compose.yml
  devops/docker/Base.Dockerfile
  devops/docker/Node.Dockerfile
  devops/docker/NodeExposed.Dockerfile
  devops/kubernetes/main.ts
  devops/kubernetes/src/cronjob.ts
  scripts/build.sh
  services/17kmmrbot/.env.example
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/index.ts
  services/17kmmrbot/src/services/leaderboard.ts
  services/17kmmrbot/tsconfig.json
  services/shared/package.json
Labels: release

#44 Pool tracking reducer in FSM
  services/17kmmrbot/src/commands/dev.ts
  services/fsm/.vscode/settings.json
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/assets/items.json
  services/fsm/src/assets/s1_units.json
  services/fsm/src/assets/units.json
  services/fsm/src/index.ts
  services/fsm/src/inversify.config.ts
  services/fsm/src/reducers/private/privatePlayerState.ts
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/fsm/src/reducers/public/poolReducer.ts
  services/fsm/src/services/poolCalculator.ts
  services/fsm/tsconfig.json
  services/shared/src/pool.ts
  services/shared/src/state.ts
Labels: enhancement

#48 Create interim !left bot command to display the remaining amount of units left for a specific unit
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/left.ts
  services/17kmmrbot/src/inversify.config.ts
  services/fsm/package.json
  services/fsm/src/services/poolCalculator.ts
  services/fsm/src/services/stateTransformer.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/assets/items.json
  services/shared/src/assets/s1_units.json
  services/shared/src/assets/units.json
  services/shared/src/units.ts
  services/shared/tsconfig.json
Labels: enhancement

#49 First pool viewer features
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/dev.ts
  services/17kmmrbot/src/commands/left.ts
  services/17kmmrbot/src/inversify.config.ts
  services/fsm/.vscode/settings.json
  services/fsm/package-lock.json
  services/fsm/package.json
  services/fsm/src/index.ts
  services/fsm/src/inversify.config.ts
  services/fsm/src/reducers/private/privatePlayerState.ts
  services/fsm/src/reducers/public/lobbyReducer.ts
  services/fsm/src/reducers/public/poolReducer.ts
  services/fsm/src/services/poolCalculator.ts
  services/fsm/src/services/stateTransformer.ts
  services/fsm/tsconfig.json
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/assets/items.json
  services/shared/src/assets/s1_units.json
  services/shared/src/assets/units.json
  services/shared/src/pool.ts
  services/shared/src/state.ts
  services/shared/src/units.ts
  services/shared/tsconfig.json
Labels: release

#50 Now excluding Underlords from pool calculations
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/left.ts
  services/fsm/.vscode/settings.json
  services/fsm/package.json
  services/fsm/src/services/poolCalculator.ts
  services/shared/package.json
  services/shared/src/assets/s1_units.json
Labels: release

#54 Gitleaks setup
  .github/workflows/gitleaks.yml
Labels: enhancement, infrastructure, release

#52 Added unit aliases to query with the bot
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/left.ts
  services/backend/package-lock.json
  services/shared/src/assets/unit_mappings.json
  services/shared/src/units.ts
Labels: enhancement

#57 HA Setup
  .gitlab-ci.yml
  .vscode/settings.json
  devops/kubernetes/imports/config.istio.io/adapter.ts
  devops/kubernetes/imports/config.istio.io/template.ts
  devops/kubernetes/imports/databases.spotahome.com/redisfailover.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafka.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkabridge.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkaconnect.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkaconnects2i.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkamirrormaker.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkamirrormaker2.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkarebalance.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkauser.ts
  devops/kubernetes/imports/networking.istio.io/gateway.ts
  devops/kubernetes/imports/networking.istio.io/serviceentry.ts
  devops/kubernetes/imports/networking.istio.io/sidecar.ts
  devops/kubernetes/main.ts
  devops/kubernetes/setup/akhq.yaml
  devops/kubernetes/setup/redis-operator.yaml
  devops/kubernetes/src/cronjob.ts
  devops/kubernetes/src/redis-commander.ts
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/connectors/redis.ts
Labels: infrastructure, rework

#58 HA Release & Deployment to new cluster
  .gitlab-ci.yml
  .vscode/settings.json
  devops/kubernetes/imports/config.istio.io/adapter.ts
  devops/kubernetes/imports/config.istio.io/template.ts
  devops/kubernetes/imports/databases.spotahome.com/redisfailover.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafka.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkabridge.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkaconnect.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkaconnects2i.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkamirrormaker.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkamirrormaker2.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkarebalance.ts
  devops/kubernetes/imports/kafka.strimzi.io/kafkauser.ts
  devops/kubernetes/imports/networking.istio.io/gateway.ts
  devops/kubernetes/imports/networking.istio.io/serviceentry.ts
  devops/kubernetes/imports/networking.istio.io/sidecar.ts
  devops/kubernetes/main.ts
  devops/kubernetes/setup/akhq.yaml
  devops/kubernetes/setup/redis-operator.yaml
  devops/kubernetes/src/cronjob.ts
  devops/kubernetes/src/redis-commander.ts
  services/17kmmrbot/package-lock.json
  services/17kmmrbot/package.json
  services/17kmmrbot/src/commands/left.ts
  services/backend/package-lock.json
  services/shared/package-lock.json
  services/shared/package.json
  services/shared/src/assets/unit_mappings.json
  services/shared/src/connectors/redis.ts
  services/shared/src/units.ts
Labels: infrastructure, release

#63 Setup EFK stack
  .vscode/settings.json
  devops/kubernetes/cdk8s.yaml
  devops/kubernetes/imports/apm.k8s.elastic.co/apmserver.ts
  devops/kubernetes/imports/beat.k8s.elastic.co/beat.ts
  devops/kubernetes/imports/elasticsearch.k8s.elastic.co/elasticsearch.ts
  devops/kubernetes/imports/enterprisesearch.k8s.elastic.co/enterprisesearch.ts
  devops/kubernetes/imports/kibana.k8s.elastic.co/kibana.ts
  devops/kubernetes/main.ts
  devops/kubernetes/package.json
  devops/kubernetes/src/fluentd/config.ts
Labels: enhancement, infrastructure
